'use server';

import { revalidatePath } from "next/cache";
import { Order, Product } from "@/core/types";
import { redirect } from "next/navigation";
import { productImageService } from '@/services/product-image';
import { productService } from '@/features/products/service';
import { orderService } from '@/features/orders/service';

export async function updateOrderStatus(orderId: string, newStatus: Order['status']) {
  try {
    await orderService.updateOrder(orderId, { status: newStatus });
    revalidatePath("/admin/dashboard");
    return { success: true };
  } catch (error) {
    console.error("Failed to update order status:", error);
    if (error instanceof Error && error.message.includes('User ID not found')) {
      redirect('/admin/login');
    }
    return { success: false, error: "עדכון סטטוס הזמנה נכשל." };
  }
}

export async function updateOrderPaymentStatus(orderId: string, newStatus: Order['paymentStatus']) {
  try {
    await orderService.updateOrder(orderId, { paymentStatus: newStatus });
    revalidatePath("/admin/dashboard");
    return { success: true };
  } catch (error) {
    console.error("Failed to update order payment status:", error);
    if (error instanceof Error && error.message.includes('User ID not found')) {
      redirect('/admin/login');
    }
    return { success: false, error: "עדכון סטטוס תשלום נכשל." };
  }
}

export async function deleteProductAction(productId: string) {
  try {
    await productService.deleteProduct(productId);
    revalidatePath("/admin/dashboard");
    revalidatePath("/admin/products");
    return { success: true };
  } catch (error) {
    console.error("Failed to delete product:", error);
    if (error instanceof Error && error.message.includes('User ID not found')) {
      redirect('/admin/login');
    }
    return { success: false, error: "מחיקת מוצר נכשלה." };
  }
}

export async function createProductAction(formData: FormData) {
  try {
    const imageFile = formData.get("image") as File | null;
    let imageURL: string | undefined;

    if (imageFile && imageFile.size > 0) {
      imageURL = await productImageService.uploadProductImage(imageFile, 'new-product'); // 'new-product' is a placeholder, actual ID will be generated by googleSheetService
    }

    const productData = {
      productName_HE: formData.get("productName_HE") as string,
      productName_EN: formData.get("productName_EN") as string,
      description: formData.get("description") as string,
      price: parseFloat(formData.get("price") as string),
      category: formData.get("category") as Product['category'],
      imageURL: imageURL || (formData.get("imageUrl") as string), // Use uploaded URL or existing if no new upload
    };

    await productService.createProduct(productData);
    revalidatePath("/admin/products");
    revalidatePath("/admin/dashboard");
  } catch (error) {
    console.error("Failed to create product:", error);
    if (error instanceof Error && error.message.includes('User ID not found')) {
      redirect('/admin/login');
    }
    return { success: false, error: "יצירת מוצר חדש נכשלה." };
  }
  redirect("/admin/products");
}

export async function updateProductAction(formData: FormData) {
  try {
    const productId = formData.get("productId") as string;
    const imageFile = formData.get("image") as File | null;
    let imageURL: string | undefined;

    if (imageFile && imageFile.size > 0) {
      imageURL = await productImageService.uploadProductImage(imageFile, productId);
    }

    const productData = {
      productName_HE: formData.get("productName_HE") as string,
      productName_EN: formData.get("productName_EN") as string,
      description: formData.get("description") as string,
      price: parseFloat(formData.get("price") as string),
      category: formData.get("category") as Product['category'],
      imageURL: imageURL || (formData.get("imageUrl") as string), // Use uploaded URL or existing if no new upload
    };

    await productService.updateProduct(productId, productData);
    revalidatePath("/admin/products");
    revalidatePath("/admin/dashboard");
  } catch (error) {
    console.error("Failed to update product:", error);
    if (error instanceof Error && error.message.includes('User ID not found')) {
      redirect('/admin/login');
    }
    return { success: false, error: "עדכון מוצר נכשל." };
  }
  redirect("/admin/products");
}