import './global.css';
import { BaseLayout } from '@/ui/layouts/BaseLayout';
import { AppProvider } from '@/core/state/AppProvider';

export const metadata = {
  title: 'Boutique E-commerce',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="he" dir="rtl">
      <body>
        <AppProvider>
          <BaseLayout>{children}</BaseLayout>
        </AppProvider>
      </body>
    </html>
  );
}
